version: "3.9"

services:
  server:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - '3306:3306'
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root"
      interval: 2s
      timeout: 30s
      retries: 10

volumes:
  my-db:

